### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by paperclypse** [garbados/the-longtime-game#2]
I got a few rounds into the game and hit a crash. The crash happened when I hit enter. Here's the error report:

```
! Press enter to proceed.

Exception in thread "main" java.lang.IllegalArgumentException: Value out of range for int: Infinity
	at clojure.lang.RT.intCast(RT.java:1250)
	at the_longtime_game.core$shift_population.invokeStatic(core.clj:714)
	at the_longtime_game.core$shift_population.invoke(core.clj:709)
	at the_longtime_game.core$begin_month.invokeStatic(core.clj:762)
	at the_longtime_game.core$begin_month.invoke(core.clj:760)
	at the_longtime_game.repl$do_month.invokeStatic(repl.clj:535)
	at the_longtime_game.repl$do_month.invoke(repl.clj:530)
	at the_longtime_game.game$game_loop$fn__2759.invoke(game.clj:105)
	at clojure.lang.Iterate.reduce(Iterate.java:81)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at the_longtime_game.game$game_loop.invokeStatic(game.clj:103)
	at the_longtime_game.game$game_loop.invoke(game.clj:101)
	at the_longtime_game.game$_main.invokeStatic(game.clj:117)
	at the_longtime_game.game$_main.doInvoke(game.clj:115)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at the_longtime_game.game.main(Unknown Source)
```

Happy to provide any extra info that might be helpful!

**Comment by garbados** [comment]
The crash occurred while the game was updating the herd's population. Logarithms are used to even out changes in population curves, but when the difference between the "optimal" and actual population is 0, log(0) is Infinity, which causes this issue. 

The problematic code has been fixed in v0.1.2 https://github.com/garbados/the-longtime-game/blob/v0.1.2/src/the_longtime_game/core.clj#L714

**Comment by garbados** [comment]
A fix has been issued in the latest release. I'll close this issue when it's confirmed resolved. https://github.com/garbados/the-longtime-game/releases/tag/v0.1.2
