### ISSUE TITLE
Crash when 'search' command used with no arguments

### ISSUE THREAD

**Issue by skeetermurphy** [garbados/the-longtime-game#4]
ran 'search' and pressed enter (no arguments to search command). Crashed.

I know, 'user error' but was unexpected.

`search 
Exception in thread "main" Syntax error compiling at (/tmp/form-init13614255524592379125.clj:1:74).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ArityException: Wrong number of args (1) passed to: the-longtime-game.repl/fn--1989
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.RestFn.invoke(RestFn.java:412)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at the_longtime_game.repl$handle_read_line.invokeStatic(repl.clj:43)
	at the_longtime_game.repl$handle_read_line.invoke(repl.clj:26)
	at the_longtime_game.repl$prompt_text.invokeStatic(repl.clj:52)
	at the_longtime_game.repl$prompt_text.doInvoke(repl.clj:47)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at the_longtime_game.repl$select_from_options.invokeStatic(repl.clj:70)
	at the_longtime_game.repl$select_from_options.doInvoke(repl.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at the_longtime_game.repl$select_from_options.invokeStatic(repl.clj:79)
	at the_longtime_game.repl$select_from_options.doInvoke(repl.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at the_longtime_game.repl$select_from_options.invokeStatic(repl.clj:79)
	at the_longtime_game.repl$select_from_options.doInvoke(repl.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at the_longtime_game.repl$select_from_options.invokeStatic(repl.clj:79)
	at the_longtime_game.repl$select_from_options.doInvoke(repl.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at the_longtime_game.repl$select_from_options.invokeStatic(repl.clj:79)
	at the_longtime_game.repl$select_from_options.doInvoke(repl.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at the_longtime_game.repl$select_from_options.invokeStatic(repl.clj:79)
	at the_longtime_game.repl$select_from_options.doInvoke(repl.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at the_longtime_game.repl$select_from_options.invokeStatic(repl.clj:79)
	at the_longtime_game.repl$select_from_options.doInvoke(repl.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at the_longtime_game.repl$select_from_options.invokeStatic(repl.clj:79)
	at the_longtime_game.repl$select_from_options.doInvoke(repl.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at the_longtime_game.repl$select_from_options.invokeStatic(repl.clj:79)
	at the_longtime_game.repl$select_from_options.doInvoke(repl.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at the_longtime_game.repl$select_from_options.invokeStatic(repl.clj:79)
	at the_longtime_game.repl$select_from_options.doInvoke(repl.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at the_longtime_game.repl$select_project.invokeStatic(repl.clj:320)
	at the_longtime_game.repl$select_project.invoke(repl.clj:309)
	at the_longtime_game.repl$select_month_projects$fn__2124.invoke(repl.clj:337)
	at clojure.lang.LongRange.reduce(LongRange.java:233)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at the_longtime_game.repl$select_month_projects.invokeStatic(repl.clj:333)
	at the_longtime_game.repl$select_month_projects.invoke(repl.clj:331)
	at the_longtime_game.repl$do_month.invokeStatic(repl.clj:532)
	at the_longtime_game.repl$do_month.invoke(repl.clj:523)
	at the_longtime_game.game$game_loop$fn__2818.invoke(game.clj:105)
	at clojure.lang.Iterate.reduce(Iterate.java:81)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at the_longtime_game.game$game_loop.invokeStatic(game.clj:103)
	at the_longtime_game.game$game_loop.invoke(game.clj:101)
	at the_longtime_game.game$_main.invokeStatic(game.clj:117)
	at the_longtime_game.game$_main.doInvoke(game.clj:115)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:380)
	at user$eval140.invokeStatic(form-init13614255524592379125.clj:1)
	at user$eval140.invoke(form-init13614255524592379125.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more
`

**Comment by garbados** [comment]
ah yes, that indeed is an unhandled case. i'll look into it.

**Comment by garbados** [comment]
for now just... don't do that 🙃
